image_size: 64
num_channels: 128
num_head_channels: 64
num_res_blocks: 2
num_heads: 4
num_heads_upsample: -1
num_head_channels: -1
attention_resolutions: "16, 8"
channel_mult: ""
dropout: 0.0
class_cond: false
use_checkpoint: false
use_scale_shift_norm: true
resblock_updown: false
use_fp16: false
use_new_attention_order: false
learn_sigma: false
diffusion_steps: 1000
noise_schedule: "linear"
timestep_respacing: ""
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
classifier_scale: 0
classifier_use_fp16: false
classifier_width: 128
classifier_depth: 2
classifier_attention_resolutions: "32,16,8"
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: "attention"
lr_kernel_n_std: 2
num_samples: 188
show_progress: true
clip_denoised: true
use_ddim: false

latex_name: RePaint
method_name: Repaint
model_path: ./ddpm/model/ema_0.9999_4000000.pt
name: repaint
inpa_inj_sched_prev: true
n_jobs: 10
print_estimated_vars: true
inpa_inj_sched_prev_cumnoise: false
schedule_jump_params:
  t_T: 1000
  n_sample: 1
  jump_length: 10
  jump_n_sample: 10
data:
  eval:
    paper_face_mask:
      mask_loader: true
      gt_path: ./data/nc_test/
      mask_path: ./data/mask_test/
      image_size: 64
      class_cond: false
      deterministic: true
      random_crop: false
      random_flip: false
      return_dict: true
      drop_last: false
      batch_size: 1
      return_dataloader: true
      offset: 0
      max_len: 188
      paths:
        srs: ./data/inpainted_results/inpainted
        lrs: ./data/inpainted_results/gt_masked
        gts: ./data/inpainted_results/gt
        gt_keep_masks: ./data/inpainted_results/gt_keep_mask